### ISSUE TITLE
Cannot disable non-root policy azwi-proxy cva

### ISSUE THREAD

**Issue by ldardick** [Azure/azure-workload-identity#1009]
**Describe the bug**
The admission webhook injects `azwi-proxy` as a sidecar container. The injected container defines a `securityContext` that defines that the container will run as non-root.

```
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
```

However, in some scenarios this may violate the existing non-root policy defined by the pod causing the sidecar container not being able to progress.

```
containerStatuses:
    - name: azwi-proxy
      state:
        waiting:
          reason: CreateContainerConfigError
          message: >-
            container's runAsUser breaks non-root policy (pod:
            "[redacted]([redacted])",
            container: azwi-proxy)
```

**Steps To Reproduce**
1. Install version `1.1.0` of the admission webhook
2. Install `ExternalDNS` configuring it to run using `azwi-proxy`. The following values can be used:
```
  provider: azure-private-dns
  azure:
    tenantId: [tenant-id]
    useManagedIdentityExtension: true
  podLabels:
    azure.workload.identity/use: "true"
  podAnnotations:
    azure.workload.identity/inject-proxy-sidecar: "true"
  serviceAccount:
    create: false
    name: external-dns-kubesa
  replicas: 1
  podSecurityContext:
    fsGroup: 65534
    runAsUser: 0
```

**Expected behavior**
The admission webhook chart should allow configuring if the sidecar proxy will run as root or not. The repro steps includes ExternalDNS, but the same may apply to other scenarios where the pod defines a `securityContext` 

**Logs**
N/A, the container won't be able to progress

**Environment**

- Kubernetes version (use `kubectl version`): 1.25.6
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):  Ubuntu 22.04.2 LTS
- Kernel (e.g. `uname -a`): 5.15.0-1039-azure
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): Azure CNI
- Others: N/A

**Additional context**
N/A

**Comment by ldardick** [comment]
Edited the original repro steps (which explained how to replicate using ExternalDNS) to replace them with steps that doesn't depend on a third party chart and can be tested isolated.

**Comment by SaiVamsi95** [comment]
@ldardick FYI: 
The same issue is happening with Velero deployment as well. Unable to store PVC data with restic when using azure workload identity to access Azure storage account.

**Comment by ldardick** [comment]
> @ldardick FYI: The same issue is happening with Velero deployment as well. Unable to store PVC data with restic when using azure workload identity to access Azure storage account.

For what it's worth, if you downgrade to `1.0.0`, that version doesn't have the security context hardcoded and works

**Comment by kengibous** [comment]
@SaiVamsi95 

FWIW i got my node agent pods to start by adding the following to my values.yaml

```
nodeAgent:  
  podSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true 
```
