### ISSUE TITLE
Unexpected Behaviour for the workload identity on AKS, federated token not created inside pod(workload identity not working due to this)

### ISSUE THREAD

**Issue by sahilvarmacsi** [Azure/azure-workload-identity#1023]
**Describe the bug**:

Wierd bug federated token is not created inside pod

**Steps To Reproduce**
Took these steps for setting up the workload identity on aks:
```bash
az extension add --name aks-preview

az extension update --name aks-preview

az feature register --name EnableOIDCIssuerPreview --namespace Microsoft.Container --subscription “{subscriptionId}”

az aks update -n {nameofCluster} -g (resourceGroupName} --enable-oidc-issuer
```
After taking these steps the OIDC issuer URL got enabled and I went to an app registration and created a federated credential.

Ran these commands for getting workload identity pods and connection with azure ad:
```bash
helm repo add azure-workload-identity https://azure.github.io/azure-workload-identity/charts

helm repo update

helm install workload-identity-webhook azure-workload-identity/workload-identity-webhook \
   --namespace azure-workload-identity-system \
   --create-namespace \
   --set azureTenantID="${AZURE_TENANT_ID}"
```

Later I used this code for service account and deployment:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-sa
  namespace: iam-identity-dev
  annotations:
    azure.workload.identity/client-id: -----------------
    azure.workload.identity/tenant-id: --------------------
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: azcli-deployment
  namespace: iam-identity-dev
  annotations:
    azure.workload.identity/inject-proxy-sidecar: "true"
  labels:
    app: azcli
    azure.workload.identity/use: "true" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azcli
  template:
    metadata:
      labels:
        app: azcli
    spec:
      serviceAccountName: iam-sa
      containers:
        - name: azcli
          image: mcr.microsoft.com/azure-cli:latest
          command:
            - "/bin/bash"
            - "-c"
            - "sleep infinity"
```
            
The az cli pod got deployed. 

I used this command to enter into pod : 

kubectl exec azcli-deployment-9545fd5f9-2dlb8 -n namespace-name

when I am trying to get out of the federated token file with this command :  cat $AZURE_FEDERATED_TOKEN_FILE

I am not getting any output. (Similar thing I have done on a different aks cluster few months ago and it is working perfectly till date and getting me the output)

**Expected behavior**
Federated token is not created inside pod

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`): 
1.25.6

**Additional context**
