### ISSUE TITLE
AZURE_CLIENT_ID env var is never assigned

### ISSUE THREAD

**Issue by julioct** [Azure/azure-workload-identity#1026]
**Describe the bug**
Followed the steps in [the quickstart](https://azure.github.io/azure-workload-identity/docs/quick-start.html) and the app crashes, presumably because AZURE_CLIENT_ID env var is never assigned.

I have also tried the AKS official docs [here](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster) and the result is the same.

I have tried the same AKS official docs with another cluster, same app, and things work without issues. 

I fail to find any error logs in azure-workload-identity-system. Added all logs I got below.

What am I missing? How to further troubleshoot?

**Steps To Reproduce**
1. Followed the steps in [the quickstart](https://azure.github.io/azure-workload-identity/docs/quick-start.html)
2. Get the logs:
kubectl logs <MY POD> -n <MY NAMESPACE>
F0713 06:20:46.319444       1 main.go:34] AZURE_CLIENT_ID environment variable is not set

**Expected behavior**
The AZURE_CLIENT_ID environment variable should be set.

**Logs**
kubectl logs <MY POD> -n <MY NAMESPACE>
F0713 06:20:46.319444       1 main.go:34] AZURE_CLIENT_ID environment variable is not set
```
kubectl logs -n azure-workload-identity-system -l app=workload-identity-webhook
{"level":"info","timestamp":"2023-07-13T05:56:26.993603Z","logger":"cert-rotation","caller":"/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.5.0/pkg/rotator/rotator.go:757$rotator.(*CertRotator).ensureCertsMounted","message":"certs are ready in /certs"}
{"level":"info","timestamp":"2023-07-13T05:56:26.993654Z","logger":"cert-rotation","caller":"/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.5.0/pkg/rotator/rotator.go:777$rotator.(*CertRotator).ensureReady","message":"CA certs are injected to webhooks"}
{"level":"info","timestamp":"2023-07-13T05:56:26.993721Z","logger":"entrypoint","caller":"/workspace/main.go:162$main.setupWebhook","message":"registering webhook to the webhook server"}
{"level":"info","timestamp":"2023-07-13T05:56:26.993864Z","logger":"controller-runtime.webhook","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/server.go:149$webhook.(*Server).Register","message":"Registering webhook","path":"/mutate-v1-pod"}
{"level":"info","timestamp":"2023-07-13T05:56:26.993943Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/server.go:217$webhook.(*Server).Start","message":"Starting webhook server"}
{"level":"info","timestamp":"2023-07-13T05:56:26.994507Z","logger":"controller-runtime.certwatcher","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/certwatcher/certwatcher.go:131$certwatcher.(*CertWatcher).ReadCertificate","message":"Updated current TLS certificate"}
{"level":"info","timestamp":"2023-07-13T05:56:26.994611Z","logger":"controller-runtime.webhook","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/server.go:271$webhook.(*Server).Start","message":"Serving webhook server","host":"","port":9443}
{"level":"info","timestamp":"2023-07-13T05:56:26.994630Z","logger":"controller-runtime.certwatcher","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/certwatcher/certwatcher.go:85$certwatcher.(*CertWatcher).Start","message":"Starting certificate watcher"}
{"level":"debug","timestamp":"2023-07-13T06:00:21.108728Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/admission/http.go:96$admission.(*Webhook).ServeHTTP","message":"received request","webhook":"/mutate-v1-pod","UID":"965e5684-ee19-41bb-a336-8b2df63eb9ae","kind":"/v1, Kind=Pod","resource":{"group":"","version":"v1","resource":"pods"}}
{"level":"debug","timestamp":"2023-07-13T06:00:21.216238Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/admission/http.go:143$admission.(*Webhook).writeAdmissionResponse","message":"wrote response","webhook":"/mutate-v1-pod","code":200,"reason":"","UID":"965e5684-ee19-41bb-a336-8b2df63eb9ae","allowed":true}
{"level":"info","timestamp":"2023-07-13T05:56:32.382313Z","logger":"cert-rotation","caller":"/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.5.0/pkg/rotator/rotator.go:757$rotator.(*CertRotator).ensureCertsMounted","message":"certs are ready in /certs"}
{"level":"info","timestamp":"2023-07-13T05:56:32.382366Z","logger":"cert-rotation","caller":"/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.5.0/pkg/rotator/rotator.go:777$rotator.(*CertRotator).ensureReady","message":"CA certs are injected to webhooks"}
{"level":"info","timestamp":"2023-07-13T05:56:32.382454Z","logger":"entrypoint","caller":"/workspace/main.go:162$main.setupWebhook","message":"registering webhook to the webhook server"}
{"level":"info","timestamp":"2023-07-13T05:56:32.382502Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/server.go:217$webhook.(*Server).Start","message":"Starting webhook server"}
{"level":"info","timestamp":"2023-07-13T05:56:32.382585Z","logger":"controller-runtime.webhook","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/server.go:149$webhook.(*Server).Register","message":"Registering webhook","path":"/mutate-v1-pod"}
{"level":"info","timestamp":"2023-07-13T05:56:32.383041Z","logger":"controller-runtime.certwatcher","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/certwatcher/certwatcher.go:131$certwatcher.(*CertWatcher).ReadCertificate","message":"Updated current TLS certificate"}
{"level":"info","timestamp":"2023-07-13T05:56:32.383129Z","logger":"controller-runtime.webhook","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/server.go:271$webhook.(*Server).Start","message":"Serving webhook server","host":"","port":9443}
{"level":"info","timestamp":"2023-07-13T05:56:32.383187Z","logger":"controller-runtime.certwatcher","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/certwatcher/certwatcher.go:85$certwatcher.(*CertWatcher).Start","message":"Starting certificate watcher"}
{"level":"debug","timestamp":"2023-07-13T06:17:45.390331Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/admission/http.go:96$admission.(*Webhook).ServeHTTP","message":"received request","webhook":"/mutate-v1-pod","UID":"dade95ef-0c27-48a8-b93a-36f7ca33beb3","kind":"/v1, Kind=Pod","resource":{"group":"","version":"v1","resource":"pods"}}
{"level":"debug","timestamp":"2023-07-13T06:17:45.500399Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/webhook/admission/http.go:143$admission.(*Webhook).writeAdmissionResponse","message":"wrote response","webhook":"/mutate-v1-pod","code":200,"reason":"","UID":"dade95ef-0c27-48a8-b93a-36f7ca33beb3","allowed":true}
```
**Environment**
AKS 

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by julioct** [comment]
@aramase Yes. Here's my yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
        - image: ghcr.io/azure/azure-workload-identity/msal-go
          name: oidc
          env:
          - name: KEYVAULT_URL
            value: https://playeconomyft.vault.azure.net/
          - name: SECRET_NAME
            value: IdentitySettings--AdminUserPassword

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client_id: 79b5f983-abca-4b63-8be2-980475f81c77
```

**Comment by aramase** [comment]
@julioct The annotation is `azure.workload.identity/client-id` with hyphen instead of the underscore (`client_id`)

**Comment by julioct** [comment]
> @julioct The annotation is `azure.workload.identity/client-id` with hyphen instead of the underscore (`client_id`)

Amazing, such a small mistake. That fixed it.

Thank you!

**Comment by relaxx22** [comment]
I have this issue as well.


The following is my yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID}
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${SERVICE_ACCOUNT_NAMESPACE}

---------------
apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: ${SERVICE_ACCOUNT_NAME}
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: ${KEYVAULT_URL}
      - name: SECRET_NAME
        value: ${KEYVAULT_SECRET_NAME}
  nodeSelector:
    kubernetes.io/os: linux


```
```
echo ${USER_ASSIGNED_CLIENT_ID}
d0e2677f-6ea7-4f92-8f85-cece5001492c
```
kubectl describe po quick-start:
```
Name:             quick-start
Namespace:        default
Priority:         0
Service Account:  workload-identity-sa
Node:             aks-agentpool02-32778246-vmss000000/10.200.247.143
Start Time:       Fri, 12 Jan 2024 15:27:23 +0800
Labels:           azure.workload.identity/use=true
Annotations:      <none>
Status:           Running
IP:               10.244.6.5
IPs:
  IP:  10.244.6.5
Containers:
  oidc:
    Container ID:   containerd://c309f1cda88ecbe4900bb2c4f28cb96faa3e47235206e940666166490c4d6bd1
    Image:          ghcr.io/azure/azure-workload-identity/msal-go
    Image ID:       ghcr.io/azure/azure-workload-identity/msal-go@sha256:c478b66969d087ffdb5c0960f42203d31d2c3a921c2e1713c8eff8c5fa6bc620
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 12 Jan 2024 15:30:22 +0800
      Finished:     Fri, 12 Jan 2024 15:30:22 +0800
    Ready:          False
    Restart Count:  5
    Environment:
      KEYVAULT_URL:  https://MYKEYVAULT.vault.azure.net/
      SECRET_NAME:   MY SECRET
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vsddv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-vsddv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m25s                  default-scheduler  Successfully assigned default/quick-start to aks-agentpool02-32778246-vmss000000
  Normal   Pulled     5m25s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 512.083083ms (512.094083ms including waiting)
  Normal   Pulled     5m23s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 513.120303ms (513.124003ms including waiting)
  Normal   Pulled     5m10s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 532.915791ms (532.926091ms including waiting)
  Normal   Created    4m40s (x4 over 5m25s)  kubelet            Created container oidc
  Normal   Started    4m40s (x4 over 5m25s)  kubelet            Started container oidc
  Normal   Pulled     4m40s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 588.396765ms (588.402066ms including waiting)
  Normal   Pulling    4m (x5 over 5m25s)     kubelet            Pulling image "ghcr.io/azure/azure-workload-identity/msal-go"
  Normal   Pulled     3m59s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 585.98832ms (585.99812ms including waiting)
  Warning  BackOff    21s (x25 over 5m23s)   kubelet            Back-off restarting failed container oidc in pod quick-start_default(3e1361ae-b005-4a19-9c95-2a305031ffb1)
```

```
kubectl logs quick-start
F0112 07:07:20.608764       1 main.go:34] AZURE_CLIENT_ID environment variable is not set
```
- Kubernetes version (use `kubectl version`): 
```

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.6
```
I tried rebuilding a cluster form scratch and retried all the steps again but issue persisted.
