### ISSUE TITLE
Annotate ServiceAccounts with the managed identity by name

### ISSUE THREAD

**Issue by dghubble** [Azure/azure-workload-identity#1093]
**Is your feature request related to a problem? Please describe.**

Is is plausible to allow Kubernetes Service Accounts to be annotated with the _name_ of a managed identity (predictable), rather than it's client_id (not predictable)?

```yaml
kind: ServiceAccount
metadata:
  annotations:
   azure.workload.identity/client-id: "a1b2c3..."
```

**Describe the solution you'd like**

Generating a bunch of service accounts, it can be cumbersome to plumb around the client_id values Azure chooses. Compared with being able to set a predictable value and having the mutating admission controller do the querying.

```yaml
kind: ServiceAccount
metadata:
  annotations:
   azure.workload.identity/managed-identity: "my-identity"
```

In AWS EKS, with OpenID Connect, service accounts are annotated with the name of an AWS role that can be assumed. Using a predictable value is quite valuable. There is no need to create a role, wait for some role id, and then annotate service accounts with an id.

```yaml
kind: ServiceAccount
metadata:
  annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role      
```

**Describe alternatives you've considered**

**Additional context**

**Comment by aglees** [comment]
I'm wondering if it's worth the time to create a workaround for this. 

One possible solution would be to have a mutating webhook, powered by a pod that has been workload identified to read from a given subscription (or wider scope), do the mapping of `resource-id` to `client-id` for `ServiceAccount` resources. 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/resource-id: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{userAssignedIdentityName}
...
````

to 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/resource-id: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{userAssignedIdentityName}
    azure.workload.identity/client-id: {clientId}
...
````

There'd still be a need to bootstrap this deployment on the cluster with Workload Identity, along with pre-creating a user assigned identity that do the mapping.

Thoughts?

**Comment by kristeey** [comment]
This feature would be very much appreciated in a GitOps setup where Managed Identities and Federated credentials are created as part of the application manifests it self.

**Comment by dghubble** [comment]
I think even just being able to specify the managed identity by resource id would be "good enough", as these are predictable. It doesn't require waiting for the workload identity to be created and assigned a client id.

```
kind: ServiceAccount
metadata:
  annotations:
   azure.workload.identity/managed-identity-resource-id: "/subscriptions/SUB/resourceGroups/GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/NAME"
```
