### ISSUE TITLE
Federated workload identities not working with kubernetes jobs

### ISSUE THREAD

**Issue by drmiru** [Azure/azure-workload-identity#1185]
## Description
Starting a container in a job does not leverage the workload identity, mapped to the service accounts. Environment variables are not injected.

### working POD deployment
```
apiVersion: v1
kind: Pod
metadata:
  name: azure-cli
  namespace: jobs
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: job-identity-sa
  containers:
    - image: mcr.microsoft.com/azure-cli:latest
      name: azurecli
      command: ["/bin/sh"]
      args: ["-c","az login --federated-token \"$(cat /var/run/secrets/azure/tokens/azure-identity-token)\" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --allow-no-subscriptions"]
  nodeSelector:
    kubernetes.io/os: linux
```

### non working job deployment
```
apiVersion: batch/v1
kind: Job
metadata:
  name: scaleup
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: job-identity-sa
  template:
    spec:
      serviceAccountName: job-identity-sa
      containers:
      - name: azure-cli
        image: mcr.microsoft.com/azure-cli:latest
        command: ["/bin/sh","-c","sleep 60; az login --federated-token \"$(cat /var/run/secrets/azure/tokens/azure-identity-token)\" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --allow-no-subscriptions"]
      restartPolicy: Never
  backoffLimit: 1
```

## Expected behavior
Containers started within jobs should also support the same feature as containers deployed as POD objects.

- Kubernetes version (use `kubectl version`): 1.26
