### ISSUE TITLE
AZURE_CLIENT_ID env var is never assigned

### ISSUE THREAD

**Issue by relaxx22** [Azure/azure-workload-identity#1231]
**Describe the bug**
Followed the steps in [the quickstart](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluste) and the app crashes, presumably because AZURE_CLIENT_ID env var is never assigned.

**Steps To Reproduce**

Followed the steps in [the quickstart](https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity)

The following is my yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID}
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${SERVICE_ACCOUNT_NAMESPACE}

---------------
apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: ${SERVICE_ACCOUNT_NAME}
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: ${KEYVAULT_URL}
      - name: SECRET_NAME
        value: ${KEYVAULT_SECRET_NAME}
  nodeSelector:
    kubernetes.io/os: linux


```
```
echo ${USER_ASSIGNED_CLIENT_ID}
d0e2677f-6ea7-4f92-8f85-cece5001492c
```
kubectl describe po quick-start:
```
Name:             quick-start
Namespace:        default
Priority:         0
Service Account:  workload-identity-sa
Node:             aks-agentpool02-32778246-vmss000000/10.200.247.143
Start Time:       Fri, 12 Jan 2024 15:27:23 +0800
Labels:           azure.workload.identity/use=true
Annotations:      <none>
Status:           Running
IP:               10.244.6.5
IPs:
  IP:  10.244.6.5
Containers:
  oidc:
    Container ID:   containerd://c309f1cda88ecbe4900bb2c4f28cb96faa3e47235206e940666166490c4d6bd1
    Image:          ghcr.io/azure/azure-workload-identity/msal-go
    Image ID:       ghcr.io/azure/azure-workload-identity/msal-go@sha256:c478b66969d087ffdb5c0960f42203d31d2c3a921c2e1713c8eff8c5fa6bc620
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 12 Jan 2024 15:30:22 +0800
      Finished:     Fri, 12 Jan 2024 15:30:22 +0800
    Ready:          False
    Restart Count:  5
    Environment:
      KEYVAULT_URL:  https://MYKEYVAULT.vault.azure.net/
      SECRET_NAME:   MY SECRET
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vsddv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-vsddv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m25s                  default-scheduler  Successfully assigned default/quick-start to aks-agentpool02-32778246-vmss000000
  Normal   Pulled     5m25s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 512.083083ms (512.094083ms including waiting)
  Normal   Pulled     5m23s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 513.120303ms (513.124003ms including waiting)
  Normal   Pulled     5m10s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 532.915791ms (532.926091ms including waiting)
  Normal   Created    4m40s (x4 over 5m25s)  kubelet            Created container oidc
  Normal   Started    4m40s (x4 over 5m25s)  kubelet            Started container oidc
  Normal   Pulled     4m40s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 588.396765ms (588.402066ms including waiting)
  Normal   Pulling    4m (x5 over 5m25s)     kubelet            Pulling image "ghcr.io/azure/azure-workload-identity/msal-go"
  Normal   Pulled     3m59s                  kubelet            Successfully pulled image "ghcr.io/azure/azure-workload-identity/msal-go" in 585.98832ms (585.99812ms including waiting)
  Warning  BackOff    21s (x25 over 5m23s)   kubelet            Back-off restarting failed container oidc in pod quick-start_default(3e1361ae-b005-4a19-9c95-2a305031ffb1)
```

```
kubectl logs quick-start
F0112 07:07:20.608764       1 main.go:34] AZURE_CLIENT_ID environment variable is not set
```
- Kubernetes version (use `kubectl version`): 
```

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.6
```
I tried rebuilding a cluster form scratch and retried all the steps again but issue persisted. 

This is similar to https://github.com/Azure/azure-workload-identity/issues/1026#top except this time I did provide correct annotation to the service account yaml
