### ISSUE TITLE
Kubernetes native sidecar not supported

### ISSUE THREAD

**Issue by YvesZelros** [Azure/azure-workload-identity#1312]
**Describe the bug**

AWI remove the field **_restartPolicy_** on init containers that break the support of [Kubernetes native sidecar](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/)

**Steps To Reproduce**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-deployment
  template:
    metadata:
      labels:
        app: simple-deployment
        azure.workload.identity/use: "true"
    spec:
      initContainers:
        - command:
            - "/bin/sh"
            - "-c"
            - "while true; do echo 'hello from init'; sleep 1; done"
          image: busybox
          name: init
          restartPolicy: Always
      containers:
        - command:
            - "/bin/sh"
            - "-c"
            - "while true; do echo 'hello from main'; sleep 1; done"
          image: busybox
          name: main
```
**Expected behavior**

The main container must be running and not waiting the end of the init container as the init container is a native sidecar (restartPolicy = Always).

**Logs**
NAME                                 READY   STATUS     RESTARTS   AGE
simple-deployment-7854b77d4b-hbs7r   0/1     Init:0/1   0          3m35s

**Environment**
- Kubernetes version (use `kubectl version`): Server Version: v1.29.2
- Cloud provider or hardware configuration: AKS

**Additional context**
https://github.com/istio/istio/issues/49221
