### ISSUE TITLE
Add the configmap as part of `kustomization.yaml` using `configMapGenerator` and use `envsubst` to populate the value

### ISSUE THREAD

**Issue by aramase** [Azure/azure-workload-identity#28]
What do you think of adding the configmap as part of `kustomization.yaml` using `configMapGenerator` and use `envsubst` to populate the value, for example: 

```yaml
...
configMapGenerator:
- name: aad-pi-config
  literals:
  - AZURE_TENANT_ID="${AZURE_TENANT_ID:-}"
  - AZURE_ENVIRONMENT="${AZURE_ENVIRONMENT:-AzurePublicCloud}"
...
```

```bash
export AZURE_TENANT_ID="..."
export AZURE_ENVIRONMENT="..."

kustomize build config/default | envsubst | kubectl apply -f -
```

(non-blocking, can be a follow-up)

_Originally posted by @chewong in https://github.com/Azure/aad-pod-managed-identity/pull/25#discussion_r630624184_
