### ISSUE TITLE
Admissions Webhook Breaks If Other Projected Tokens Are In Use

### ISSUE THREAD

**Issue by ekristen** [Azure/azure-workload-identity#357]
**Describe the bug**

The Admissions Webhook fails to account for if there are other projected source tokens already defined on a workload and just attempts to add it's own.

**Steps To Reproduce**

1. Install AZWI
2. Setup SA Account with AZWI Annotations
3. Create a Pod that Projects it's own Token

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: build-robot
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
```

**Expected behavior**

AZWI should be smart enough to understand that the mountPath /var/run/secrets/tokens is already set and not try and set it again.

**Logs**

```
The Pod "nginx" is invalid: spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/var/run/secrets/tokens": must be unique
```

**Environment**

- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**
