### ISSUE TITLE
May I know Azure workload identity works for aks virtual-node-aci-linux

### ISSUE THREAD

**Issue by SandeepCitigori** [Azure/azure-workload-identity#381]
Currently, we are using Azure AD Pod Identity for our aks clusters.
We are exploring Azure AD workload identity and able to install using the below links and see it works in nodes as per the given example.
https://azure.github.io/azure-workload-identity/docs/introduction.html
https://github.com/Azure/azure-workload-identity

As mentioned in the 7th point or end of this page, https://azure.github.io/azure-workload-identity/docs/quick-start.html

I have deployed the workload and am able to access the key vault secret via the azure token.

Then I have updated the yaml with nodeSelector & tolerations to install in the virtual-node-aci-linux. Upon deploy, the pod is running but not able to access the keyvault secret.

```
Deploy pod:
apiVersion: v1
kind: Pod
metadata:
  name: quick-start-vk
  namespace: ${SERVICE_ACCOUNT_NAMESPACE}
spec:
  serviceAccountName: ${SERVICE_ACCOUNT_NAME}
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go:latest
      name: oidc
      env:
      - name: KEYVAULT_NAME
        value: ${KEYVAULT_NAME}
      - name: SECRET_NAME
        value: ${KEYVAULT_SECRET_NAME}
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
    - key: azure.com/aci
      effect: NoSchedule

```
Error when running kubectl logs podname:
`E0215 15:21:21.216383       1 token_credential.go:43] 'failed to read the service account token from the filesystem' err='open /var/run/secrets/azure/tokens/azure-identity-token: no such file or directory'`
