### ISSUE TITLE
Affinity not passed to deployment in Helm chart

### ISSUE THREAD

**Issue by mrowken** [Azure/azure-workload-identity#456]
**Describe the bug**
In Azure AD Workload Identity Helm Chart there is documented parameter `affinity` [link](https://github.com/Azure/azure-workload-identity/tree/main/charts/workload-identity-webhook#parameters), but it seems like not used by the deployment created from this helm chart.

**Steps To Reproduce**
Follow instructions to install helm chart [here](https://github.com/Azure/azure-workload-identity/tree/main/charts/workload-identity-webhook#install-chart)
```bash
helm install -n azure-workload-identity-system [RELEASE_NAME] azure-workload-identity/workload-identity-webhook --create-namespace -f values.yaml
```

I have used below as values.yaml:
```yaml
azureTenantID: "<REDACTED>"
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: kubernetes.azure.com/mode
          operator: In
          values:
          - system
      weight: 100
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
```

**Expected behavior**
Parameter `affinity` defined in [values.yaml](https://github.com/Azure/azure-workload-identity/blob/main/charts/workload-identity-webhook/values.yaml) is passed to deployment, so it can instruct kubernetes scheduler to assign workload-identity-webhook POD to run on dedicated system nodepool.

**Logs**

**Environment**

- Kubernetes version: v1.23.5
- Cloud provider or hardware configuration: Azure AKS

**Additional context**
