### ISSUE TITLE
failed to create confidential client err=the Authority does not appear to use https

### ISSUE THREAD

**Issue by mo-saeed** [Azure/azure-workload-identity#611]
Hi, 

I tried to follow the same procedure as here https://azure.github.io/azure-workload-identity/docs/quick-start.html#5-create-a-kubernetes-service-account using user-assigned managed identity but in the pod log i see this error

```
E1026 12:41:17.836791       1 token_credential.go:49] "failed to create confidential client" err="the Authority(TENANT_ID/oauth2/token) does not appear to use https"
```
Can you please advise what could be the issue here ?

**Comment by aramase** [comment]
`AZURE_AUTHORITY_HOST` env var would be the same irrespective of Azure AD Apps/user-assigned managed identity. Please share the following details:

1. What version of the webhook are you using?
2. Final pod yaml (`kubectl get pod <pod name> -o yaml` (redact client id)
3. Final service account yaml (`kubectl get serviceaccount <name> -o yaml` (redact client id)

**Comment by mo-saeed** [comment]
Thanks @aramase 
- latest version :v0.14.0

- the yaml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"quick-start","namespace":"default"},"spec":{"containers":[{"env":[{"name":"KEYVAULT_NAME","value":"test-workload-identity"},{"name":"KEYVAULT_URL","value":"https://test-workload-identity.vault.azure.net/"},{"name":"SECRET_NAME","value":"my-secret"}],"image":"ghcr.io/azure/azure-workload-identity/msal-go","name":"oidc"}],"nodeSelector":{"kubernetes.io/os":"linux"},"securityContext":{"fsGroup":1001,"runAsUser":1001},"serviceAccountName":"workload-identity-sa"}}
  name: quick-start
  namespace: default
spec:
  containers:
  - env:
    - name: KEYVAULT_NAME
      value: test-workload-identity
    - name: KEYVAULT_URL
      value: https://test-workload-identity.vault.azure.net/
    - name: SECRET_NAME
      value: my-secret
    image: ghcr.io/azure/azure-workload-identity/msal-go
    imagePullPolicy: Always
    name: oidc
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tgjhd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ******* --> changed by me
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount: workload-identity-sa
  serviceAccountName: workload-identity-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-tgjhd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-10-26T13:27:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-10-26T16:27:31Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-10-26T16:27:31Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-10-26T13:27:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b4d5f211bdd4f6373ef3d597d5b84c7756aa91e97e7f890ad3e8bc182e408830
    image: ghcr.io/azure/azure-workload-identity/msal-go:latest
    imageID: ghcr.io/azure/azure-workload-identity/msal-go@sha256:1e0bfde31b3dac25b8025a5d3d284e95d102af22033073ac045e9add45e03991
    lastState:
      terminated:
        containerID: containerd://977b682d2afa99fe47e670ab6ceb24b16f99d0c0b89b512e1bef93efc926b79b
        exitCode: 1
        finishedAt: "2022-10-26T16:24:56Z"
        reason: Error
        startedAt: "2022-10-26T16:17:26Z"
    name: oidc
    ready: true
    restartCount: 21
    started: true
    state:
      running:
        startedAt: "2022-10-26T16:27:31Z"
  hostIP: 10.1.192.177
  phase: Running
  podIP: 10.1.193.118
  podIPs:
  - ip: 10.1.193.118
  qosClass: BestEffort
  startTime: "2022-10-26T13:27:37Z"
```

- service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: *****--> changed by me
    azure.workload.identity/tenant-id: ***** --> changed by me
  creationTimestamp: "2022-10-26T12:22:12Z"
  labels:
    azure.workload.identity/use: "true"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:azure.workload.identity/client-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:azure.workload.identity/use: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-10-26T12:22:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:azure.workload.identity/tenant-id: {}
    manager: kubectl-edit
    operation: Update
    time: "2022-10-26T13:27:09Z"
  name: workload-identity-sa
  namespace: default
  resourceVersion: "444004502"
  uid: 7d92c03e-381c-4091-946b-78ded9e0edbf
secrets:
- name: workload-identity-sa-token-p7vjh
```
