### ISSUE TITLE
Side car Container not working

### ISSUE THREAD

**Issue by dbg-raghulkrishna** [Azure/azure-workload-identity#651]
**Describe the bug**
Side car container with azure login --identity not working
**Steps To Reproduce**
```
Kubectl  apply -f -
kind: ServiceAccount
apiVersion: v1
metadata:
  name: quick-start
  namespace: default
  labels:
    azure.workload.identity/use: 'true'
  annotations:
    azure.workload.identity/client-id: ""

--- 
apiVersion: v1
kind: Pod
metadata:
  name: quick-start1
  namespace: default
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/inject-proxy-sidecar: "true"
spec:
  serviceAccountName: quick-start
  containers:
    - image: mcr.microsoft.com/azure-cli
      name: oidc
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 1000;done"]
  nodeSelector:
    kubernetes.io/os: linux
```
    
**Expected behavior**
Successful login

**Logs**
Log from Side car
![image](https://user-images.githubusercontent.com/106546936/204621184-ad0930e4-adb1-404e-9c40-90be88d23717.png)

Log from Container
![image](https://user-images.githubusercontent.com/106546936/204621231-cc22d515-15b5-4b8b-a409-6403d15498d1.png)

**Environment**

- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):  cat /etc/os-release`
- Kernel (e.g. `uname -a`): Linux quick-start1 5.4.0-1091-azure #96~18.04.1-Ubuntu SMP Tue Aug 30 19:15:32 UTC 2022 x86_64 Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**
