### ISSUE TITLE
Can't use msal-node with workflow-identity on my AKD

### ISSUE THREAD

**Issue by SaillyMaxence** [Azure/azure-workload-identity#671]
Hello, 

i have few questions, i tried to use worfkload identity managed on my AKS for getting secret in my KV, i reproduce the microsoft tutorial, and use go-msal from : https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/msal.html like this : 

```
apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: "https://test-maxence.vault.azure.net/"
      - name: SECRET_NAME
        value: "yes"
  nodeSelector:
    kubernetes.io/os: linux
```
And it work's 

my application use node-js i tried the node-msal package like this : 

```
apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-node
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: "https://test-maxence.vault.azure.net/"
      - name: SECRET_NAME
        value: "yes"
  nodeSelector:
    kubernetes.io/os: linux
```
so i tried to take the code source of the msal-node exemple in repository, to create my own docker build, i just download it and create image without update any file, 

got this error : 

TypeError: entry.trim is not a function

Error: Failed to get token silently

To reproduce : 

- Download sources : https://github.com/Azure/azure-workload-identity/tree/main/examples/msal-node
- Build docker image 
- apply it on kubectl

**Expected behavior**
console.log(`successfully got secret, secret=${secret.value}`)

Thanks you
