### ISSUE TITLE
AZ CLI login doesn't work with workload identity

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/azure-workload-identity#682]
**Describe the bug**
I'm attempting to use the official Azure CLI docker container (https://learn.microsoft.com/en-us/cli/azure/run-azure-cli-docker) in a kubernetes pod with az workload identity to authenticate. az login command hangs indefinitely with no response. --debug and --verbose flags do not create any output either.

**Steps To Reproduce**
Create a service account, federate it to a service principal in Azure AD:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <redacted>
    azure.workload.identity/tenant-id: <redacted>
  name: testing-azure-cli-sa
  namespace: testing
```
Create manifest to run azure cli with indefinite sleep commands to keep it running (For debug/testing purposes)
```
kind: Pod
metadata:
  name: azcli
  namespace: testing
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: testing-azure-cli-sa
  containers:
  - name: azurecli
    image: mcr.microsoft.com/azure-cli:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
```
Exec into container and run az version to test that cli works, then try to login
```
azcli:/# az version
{
  "azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
azcli:/# az login --federated-token "$(cat  $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID

```

**Expected behavior**
AZ Cli would login and I could proceed to run commands.

**Logs**
None, no info is given.

**Environment**

- Kubernetes version (use `kubectl version`): AKS 1.22.15
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): "Alpine Linux v3.17" (came from azurecli container)
- Kernel (e.g. `uname -a`): Linux azcli 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**
