### ISSUE TITLE
Deployment pod is changing the webhook annotations

### ISSUE THREAD

**Issue by andre-lx** [Azure/azure-workload-identity#687]
**Describe the bug**

Since we have some namespaces with the following label `control-plane: x` we need to add the following annotation `admissions.enforcer/disabled: "true"` to the MutatingWebhookConfiguration. 

The problem is that after applying the full deployment, the workload identity pod changes the MutatingWebhookConfiguration and remove the annotation. 

**Steps To Reproduce**

Download the manifest and add the following annotation:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: azure-wi-webhook-mutating-webhook-configuration
  annotations:
    admissions.enforcer/disabled: "true"
```

Deploy the edited manifests.

```cli
kubectl apply -f azure-wi-webhook.yaml
```

After some seconds, the annotation is removed from the MutatingWebhookConfiguration. I believe is when the ca is added to the MutatingWebhookConfiguration. 

I also tried to set the annotation using helm, using the `mutatingWebhookAnnotations` and we have the same behaviour. 

**Expected behavior**

The MutatingWebhookConfiguration annotation should not be removed. 

**Environment**

- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration: Azure

**Addition context**

This is described in the known issues section at:

https://github.com/Azure/azure-workload-identity/blob/main/docs/book/src/known-issues.md#environment-variables-not-injected-into-pods-deployed-in-the-kube-system-namespace-in-an-aks-cluster

Thanks, André
