### ISSUE TITLE
azcli login works with pod but not with cronjob

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/azure-workload-identity#754]
I'm trying to get a Kubernetes CronJob running that will use azcli with workload identity.

I was able to get this working as a Pod, but trying to do the exact same thing as a CronJob fails.

The way I'm doing this, I have an Azure CLI script being passed in as a configmap and being executed.

This is the source code for the Pod version. This works flawlessly:
```
apiVersion: v1
kind: Pod
metadata:
  name: azcli
  namespace: routesync
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: routesync-secret-store-sa
  containers:
  - name: azurecli
    image: mcr.microsoft.com/azure-cli:2.45.0
    command:
      - /bin/bash
      - /scripts/routescript.sh
    volumeMounts:
    - name: routesync-script
      mountPath: /scripts
  volumes:
  - name: routesync-script
    configMap:
      name: routesync-script
      defaultMode: 0744
```

But running basically the exact same thing as a CronJob fails:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: routesync
  namespace: routesync
  labels:
    azure.workload.identity/use: "true"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: routesync-secret-store-sa
          containers:
          - name: routesync
            image: mcr.microsoft.com/azure-cli:2.45.0
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - /scripts/routescript.sh
            volumeMounts:
            - name: routesync-script
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: routesync-script
            configMap:
              name: routesync-script
              defaultMode: 0744
```

This is the log output when trying to run the cronjob:
```
ERROR: argument --username/-u: expected one argument

Examples from AI knowledge base:
az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p VerySecret --tenant contoso.onmicrosoft.com
Log in with a service principal using client secret. Use -p=secret if the first character of the password is '-'.

az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p ~/mycertfile.pem --tenant contoso.onmicrosoft.com
Log in with a service principal using client certificate.

az login -u johndoe@contoso.com -p VerySecret
Log in with user name and password. This doesn't work with Microsoft accounts or accounts that have two-factor authentication enabled. Use -p=secret if the first character of the password is '-'.

https://aka.ms/cli_ref
Read more about the command in reference docs
ERROR: Please run 'az login' to setup account.
```
I have noticed that if I remove the "use-workload-identity" metadata label from the working Pod version, I can reproduce this error, so I suspect that the CronJob is simply not using workload identity for whatever reason.

Is there a different method I have to use to get workload identity to be used by the cronjob?

**Comment by tdevopsottawa** [comment]
Resolved. A simple case of a Kubernetes syntax error (damn yamls...). The metadata label to use workload identity had to part of the spec inside the jobTemplate, not the cronjob itself.

Like this
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: routesync
  namespace: routesync
  labels:
    azure.workload.identity/use: "true"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: routesync-secret-store-sa
          containers:
          - name: routesync
            image: mcr.microsoft.com/azure-cli:2.45.0
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - /scripts/routescript.sh
            volumeMounts:
            - name: routesync-script
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: routesync-script
            configMap:
              name: routesync-script
              defaultMode: 0744
```
